### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by Pxrple** [ProperVortex/ShareX-Custom-Upload#2]
`Response parse failed.
Newtonsoft.Json.JsonReaderException: Error parsing NaN value. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseNumberNaN(ReadType readType, Boolean matched)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at ShareX.UploadersLib.CustomUploaderParser.ParseSyntaxJson(String syntaxJsonPath)
   at ShareX.UploadersLib.CustomUploaderParser.ParseSyntax(String syntax, Boolean isOutput)
   at ShareX.UploadersLib.CustomUploaderParser.Parse(String text, Boolean isOutput)
   at ShareX.UploadersLib.CustomUploaderItem.ParseResponse(UploadResult result, ResponseInfo responseInfo, CustomUploaderInput input, Boolean isShortenedURL)
   at ShareX.UploadersLib.ImageUploaders.CustomImageUploader.Upload(Stream stream, String fileName)`

**Comment by seniorlonely** [comment]
did u solved?

**Comment by yppdr** [comment]
I have the same error but the pull of Java2107 solved the problem.
#5

**Comment by 3045** [comment]
@yppdr Yeah it seems that ShareX is only looking for a JSON response, so when it doesn't see one, it freaks out and returns an incoherent error message. Glad my contribution could help! 👍

**Comment by yppdr** [comment]
Hi @Pxrple , after several tests, the version proposed by Java2107 works. 
So I think you can close your exit by mentioning the creator (@Inteliboi ).
